function run_error()
    return nil
end

assert(run_error(), "run error")
